apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hub-pod
    spec:
      containers:
      - name: hub-container
        image: yuvipanda/simplehub:v1.3
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8000
            name: hub-port
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cull-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cull-pod
    spec:
      containers:
      - name: cull-container
        image: #ADD
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8001
            name: cull-port
---
apiVersion: v1
kind: Service
metadata:
  name: hub-
spec:
  type: LoadBalancer
  selector:
    name: cull-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cull-
spec:
  type: LoadBalancer
  selector:
    name: proxy-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
